# -*- coding: utf-8 -*-
"""Praktikum1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QrXJnabV9qigU9lkKnwNTT0K_yxWNjPD
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Dataset_Kinerja_Karyawan.csv')
df.info()

df.head()

print("=== Statistika Deskriptif Skor Kinerja ===")
desc_stats = df['Skor_Kinerja'].describe()
print(desc_stats)

modus = df['Skor_Kinerja'].mode()[0]
varians = df['Skor_Kinerja'].var()
range_skor = df['Skor_Kinerja'].max() - df['Skor_Kinerja'].min()

print(f"\nModus: {modus}")
print(f"Varians: {varians:.2f}")
print(f"Range: {range_skor}")

plt.figure(figsize=(10, 6))
sns.histplot(df['Skor_Kinerja'], bins=20, kde=True, color='skyblue', edgecolor='black')
plt.axvline(df['Skor_Kinerja'].mean(), color='red', linestyle='dashed', linewidth=2, label=f"Mean: {df['Skor_Kinerja'].mean():.2f}")
plt.axvline(df['Skor_Kinerja'].median(), color='green', linestyle='dashed', linewidth=2, label=f"Median: {df['Skor_Kinerja'].median():.2f}")
plt.title('Distribusi Skor Kinerja Karyawan', fontsize=14, pad=15)
plt.xlabel('Skor Kinerja', fontsize=12)
plt.ylabel('Frekuensi', fontsize=12)
plt.legend()
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='Departemen', y='Skor_Kinerja', data=df, palette='Set2')
plt.title('Sebaran Skor Kinerja per Departemen', fontsize=14, pad=15)
plt.xlabel('Departemen', fontsize=12)
plt.ylabel('Skor Kinerja', fontsize=12)
plt.show()

plt.figure(figsize=(10, 6))
sns.barplot(x='Departemen', y='Lama_Bekerja_Tahun', data=df, errorbar=None, palette='viridis')
plt.title('Rata-rata Lama Bekerja Karyawan per Departemen', fontsize=14, pad=15)
plt.xlabel('Departemen', fontsize=12)
plt.ylabel('Lama Bekerja (Tahun)', fontsize=12)
plt.show()

"""1. Skor kinerja karyawan bervariasi cukup lebar.
Skornya ada dari 28 sampai 100 (range 72) dengan varians 152,92. Artinya ada karyawan yang berprestasi banget, tapi ada juga yang skornya rendah dan perlu dibina.

2. HR paling stabil, Finance paling beragam.
Dari standar deviasi, HR paling kecil (11,63) berarti kinerjanya paling merata. Finance paling besar (13,17) berarti kualitas kinerja antar karyawannya kurang seragam. Finance bisa dievaluasi lagi soal standar penilaian atau pelatihannya.

3. Ada beberapa karyawan outlier di boxplot.
Ada 3 outlier atas di Operasional (karyawan berprestasi, cocok dikasih promosi atau program retensi) dan 1 outlier bawah di Sales (perlu pendampingan khusus).
"""